### PR TITLE
mini notation: international alphabets support

### PR DESCRIPTION
**Pull request by ilesinge**
Implements #750 

Note that without reducing the max error message's length to 180 in the Repl (while keeping the end of the error message), the screen becomes unusable when one use a character that is not included (such as "$"). The full error message can still be found in the console as seen below.
It could be possible to do the same length reduction with the error in the console.

image

### CODE REVIEW

**Comment by felixroos** [comment]
looks like there are ways to customize the peggy error message: https://peggyjs.org/documentation.html#error-messages  maybe it is customizable enough to allow not printing all these characters and just write something like "character x cannot be used"

**Comment by ilesinge** [comment]
Having a look at the error message customization, thanks :)

**Comment by felixroos** [comment]
one potential danger i see here is that some of these chars might become useful later to be used as new operators in mini notation. so it will become a breaking change if new characters are needed that are part of this set. many programming languages reserve a bunch of words that might become language features later, even if they are never used in the end.

**Comment by ilesinge** [comment]
It's better with the customized error message, see below.

image

**Comment by felixroos** [comment]
> It's better with the customized error message, see below.

ah perfect

**Comment by ilesinge** [comment]
Regarding potential operator characters, it should be noted that the added characters do not include special characters, only letters that are not "universally" easily typeable since they are in other alphabets or include diacritics.
I'm not sure they make good candidates for operators.
We could still reduce the list though, but it would be to the detriment of some languages.

**Comment by felixroos** [comment]
> Regarding potential operator characters, it should be noted that the added characters do not include special characters, only letters that are not "universally" easily typeable since they are in other alphabets or include diacritics. I'm not sure they make good candidates for operators. 

good point! so maybe we don't need to reserve any of those then

> We could still reduce the list though, but it would be to the detriment of some languages.

i think we can keep it as is then

**Comment by felixroos** [comment]
maybe remove the 180 limit again then? More then 180 could be useful in some scenarios as some js errors are really long and might contain useful info at the end

**Comment by ilesinge** [comment]
:heavy_check_mark: Removed the 180 limit

**Comment by felixroos** [comment]
looks good, I think this is ready to merge then!

@yaxu this is pretty core / potentially tied to tidal compat so I'll ping you to ask if you have any objections?

**Comment by yaxu** [comment]
Fine by me!

**Comment by ilesinge** [comment]
Thanks!

**Pull request merged**
