### PR TITLE
clip now works like legato in tidal

### PR DESCRIPTION
**Pull request by felixroos**
- hap.duration now respects clip value
- hap.endClipped is now end*clip
- visualizations show clipped length
- clip(0) will now be silence

clip so far was only a flag. now it supports floats, making it equivalent to legato in tidal.
i did not touch legato because it would break dozens of existing patterns, as legato currently works without hap.value, so it can be used within a control param function.
in the long run, it should make sense to either refactor old patterns or implement https://github.com/tidalcycles/strudel/issues/288 . 
with just clip changed, the only breaking change is that clip(0) now brings silence, instead of, as currently, disabling clip.
In practice, clip(0) is not really in use, as it is the default behavior anyway (i haven't found a single use anywhere)

btw shoutout to henk from the workshop for inspiring the idea!

### CODE REVIEW

**Comment by felixroos** [comment]
I have now refactored usages of `legato` in the examples to `clip` .. The question is if the old legato should stay as is (illegal time manipulation) or if we should change it to be an alias of clip (like tidal).. Changing it will break a lot of existing patterns, as the current legato can be used on non-object values. 
I'd say we merge this now so people won't see any more examples of a thing that might break in the future. We can decide later if we want to do the breaking change or implement https://github.com/tidalcycles/strudel/issues/288

ok?

**Comment by felixroos** [comment]
@yaxu any objections?

**Comment by yaxu** [comment]
Sorry for being slow, looks good!

**Comment by yaxu** [comment]
> we should change it to be an alias of clip (like tidal)

actually clip/legato don't seem to be aliased in Tidal yet, will make an issue..

**Comment by telephon** [comment]
Just to be sure this is really correct?
- if `legato` is given, it overrides the sample's own duration. It is the multiple of the inter-onset time (`delta`, received from tidalcycles). For `legato = 1`, one event ends where the next starts, for `legato = 0.5` it ends in between, for `legato = 2` it overlaps fully with the next event.
- if `sustain` is given, `legato` has no effect (sustain is the total duration of an event)

**Comment by yaxu** [comment]
Yes I think that's the same as `clip`:
```js
note("c e f g").s("folkharp").clip("<0.5 1 2>")
```
https://strudel.cc/?ezJvywGYY2vq

It's not really inter-onset time though, but event duration. So `"a ~ b ~".clip(0.5)` translates to events of 1/8th of a cycle. I think is where the name 'legato' becomes problematic?

**Comment by telephon** [comment]
> So `"a ~ b ~".clip(0.5)` translates to events of 1/8th of a cycle. I think is where the name 'legato' becomes problematic?

The inter-onset time for the events in the cycle is 1/4, so it makes sense that legato 0.5 would make them 1/8. What about clip on patterns with unequal duration? There, the "clipping" should be relative to their individual duration (actually: inter onset time).

**Pull request merged**
