### PR TITLE
add midi clock support

### PR DESCRIPTION
**Pull request by felixroos**
fixes https://github.com/tidalcycles/strudel/issues/709

usage:

```js
stack(
  s("hh*4"),
  midicmd("clock*48").midi('IAC-Treiber Bus 1')
)
```

This allows manipulating the clock itself with a pattern :)
Additionally, it will fire a midi start event when the repl is started to make sure the clock is in phase.
On the very first start, it might behave weird when midi is not initialized yet...

edit: adjusted for new syntax

### CODE REVIEW

**Comment by yaxu** [comment]
Nice! I have limited experience with midi clock, but did find it can be nice to send midi start more often, say every cycle. Some synths don't like this though. It can also be fun to pattern midi starts.

Superdirt uses a 'midicmd' control to specify the different midi commands. https://tidalcycles.org/docs/configuration/MIDIOSC/midi/#synchronising-midi-clock-via-tidal

This mirrors the supercollider midi api https://doc.sccode.org/Tutorials/A-Practical-Guide/PG_08_Event_Types_and_Parameters.html#MIDI%20output

**Comment by felixroos** [comment]
> Nice! I have limited experience with midi clock, but did find it can be nice to send midi start more often, say every cycle. Some synths don't like this though. It can also be fun to pattern midi starts.

i should've looked at the tidal doc first :) yep that midicmd control sure looks nice! I've changed it to now allow:

```js
stack(
  note("<c eb f g>*2").ply(2).s("gm_acoustic_bass").sub(note(12)),
  midicmd("clock*24*2,<start stop>/2").midi('IAC-Treiber Bus 1')
)
```

I've added a an alias `clock` for `midiclock`, because the namespace seems redundant, as the control is already namespaced...

**Comment by felixroos** [comment]
I've now adding automated start stop messages on top of it, because at least ableton does not like when the midi clock ends without sending a stop. the start could theoretically be left to the user, but it seems weird to only send the stop.

**Comment by felixroos** [comment]
ok starting automatically is a good idea, because my keystep will treat a second start message as toggle, so a continuous playback wouldn't be possible without a one time start command

**Pull request merged**
