### PR TITLE
editor: enable line wrapping

### PR DESCRIPTION
**Pull request by roipoussiere**
Useful when the editor has a small width (required for #574).

### CODE REVIEW

**Comment by felixroos** [comment]
maybe also add a setting for that?

**Comment by roipoussiere** [comment]
Yes I can, but I just wonder what is the use case of don't wanting line breaks?

I like to understand user needs before adding many options, which can overload the UI at some point.

**Comment by felixroos** [comment]
> Yes I can, but I just wonder what is the use case of don't wanting line breaks?

- You could have a single line of code with a large amount of data, e.g. voicings
- You could actually want to scroll horizontally for layouting purposes, example: https://strudel.tidalcycles.org/?_usVdv9dq4rH

**Comment by roipoussiere** [comment]
Ok thanks for the explications, I'm adding the option to the settings.

**Comment by roipoussiere** [comment]
I'm waiting for #588 to be merged to avoid conflicts, as modifications takes in same places.

**Comment by felixroos** [comment]
Just fixed the conflict

**Comment by roipoussiere** [comment]
added the checkbox in last commit

**Comment by roipoussiere** [comment]
It works pretty well with different screen sizes:

image

**Comment by felixroos** [comment]
nice! so i suppose it's ready to merge?

**Comment by roipoussiere** [comment]
yep!

**Pull request merged**
