### PR TITLE
Move stuff to new register function

### PR DESCRIPTION
**Pull request by felixroos**
getting rid of all usages of `Pattern.prototype.define`,`Pattern.prototype.bootstrap`, `Pattern.patternify`, `patternifyN`

### CODE REVIEW

**Comment by felixroos** [comment]
refactoring is mostly done, removed all all old define calls + stuff that is no longer needed. Had to rename `csound` to `loadCsound` to avoid overwriting the new toplevel `csound` function. Tests still fail.. some listening / testing to do

**Comment by felixroos** [comment]
not sure how to handle this: https://github.com/tidalcycles/strudel/pull/295/commits/306004ecd2a98a9ac2e289e7f43265f7d44c9213 ref https://github.com/tidalcycles/strudel/issues/245

**Comment by yaxu** [comment]
Tidal has a 'defragment' function that combines adjacent parts with the same whole and value. Along with `sortHapsByPart` this can be 'good enough' for comparing equivalent but differently fragmented patterns in tests.

Just having a go at porting defragment..

**Comment by felixroos** [comment]
> Just having a go at porting defragment..

do you plan to add it to this PR or should we merge this one first?

**Comment by yaxu** [comment]
I can do it as a separate PR

**Pull request merged**
