### PR TITLE
repl: set document.title from @title

### LINKED ISSUE #811: Strudel metadata integration with webpage HTML <head> attributes
Ref: https://strudel.tidalcycles.org/learn/metadata

Example of `@title` -> `<title>`: https://strudel.cc/?IOOvk7YMSN4v

Use cases:
- Having multiple Strudel REPL browser tabs open and navigating to specific ones
- Web browser URL box suggestion / autocompletion help for finding previous Strudels by title

### PR DESCRIPTION
**Pull request by kasparsj**
fixes #811
(started using Strudel with multiple tabs)

### CODE REVIEW

**Comment by yaxu** [comment]
Oh nice does this mean that the title shows up in browser history as well?

**Comment by kasparsj** [comment]
good point. yes, it does, but there is a bug - I will fix - it changes the title to early

**Comment by kasparsj** [comment]
should be good to go now

**Comment by yaxu** [comment]
Excellent, thanks @kasparsj !

**Pull request merged**
