### PR TITLE
Add a search bar to the REPL Reference tab

### PR DESCRIPTION
**Pull request by netux**
Simple text input that sticks to the top.

Filters by just checking if the search term is in the entry name or synonyms, if available.

Empty search

Search matches two functions with a similar synonym

### CODE REVIEW

**Comment by yaxu** [comment]
Works for me!

**Comment by yaxu** [comment]
ok to merge @daslyfe @felixroos  ?

**Comment by felixroos** [comment]
fine with me! thanks @netux

**Comment by yaxu** [comment]
Thanks @netux !

**Pull request merged**
