### PR TITLE
Improve performance of ! (replicate)

### PR DESCRIPTION
**Pull request by yaxu**
Re-implement with weighted repeatCycles

### CODE REVIEW

**Comment by yaxu** [comment]
* `s("<bd(3,8) -!50000>")` is fine now
* `s("<bd(3,8) -!50000>")` takes a while to start, but then runs fine (although the kicks never play because it took so long to get started)
* `s("<bd(3,8) -!500000>")` says too many function arguments for some reason??

**Comment by yaxu** [comment]
Ah, `repeatCycles` itself is just `return slowcat(...Array(n).fill(pat));`.

**Comment by felixroos** [comment]
> Ah, `repeatCycles` itself is just `return slowcat(...Array(n).fill(pat));`.

that is probably because `repeatCycles` uses `slowcat(...Array(n).fill(pat))` . maybe there is a way to implement this without each element being one argument?

**Comment by felixroos** [comment]
> Ah, `repeatCycles` itself is just `return slowcat(...Array(n).fill(pat));`.

could that be implemented with a step based function like `s_cat`? maybe something like: https://strudel.cc/?0Ni_ayF8qs_Y

**Comment by yaxu** [comment]
`s("<bd(3,8) -!500000000000000000>")` now works fine :)

**Comment by felixroos** [comment]
> `s("<bd(3,8) -!500000000000000000>")` now works fine :)

great!

**Comment by yaxu** [comment]
The s_cat solution is interesting but results in missed/duplicated haps..
https://strudel.cc/?cID8aKangF3_

**Comment by yaxu** [comment]
The 9th kick is doubled up for `s("<cp  bd(3,8)!500000000000000000>")` :/

**Comment by yaxu** [comment]
I'll merge for now though!

**Comment by felixroos** [comment]
> The 9th kick is doubled up for `s("<cp bd(3,8)!500000000000000000>")` :/

hmm maybe this only happens with very very large numbers due to some overflow or float precision problems?

**Comment by yaxu** [comment]
> > The 9th kick is doubled up for `s("<cp bd(3,8)!500000000000000000>")` :/
> 
> hmm maybe this only happens with very very large numbers due to some overflow or float precision problems?

It should all be rationals so shouldn't be precision.

500000000000000000 is about 8000000000 years though so not a huge issue for the next 200000000 generations of people

**Pull request merged**
