### PR TITLE
add createParam + createParams

### PR DESCRIPTION
**Pull request by felixroos**
as requested by @guillaume-leo, this PR contains the methods `createParam` + `createParams` to be able to use custom params, e.g. for osc:

```js
const dudu = createParam('dudu'); // for single params
const { dada, dodo} = createParams('dada', 'dodo'); // multiple params
```

the param can then be used either to start a pattern, or as a pattern method:

```js
dudu('xxx').dada('yyy').osc(); // {dudu:'hehe', dada: 'yyy'}, osc message ['dudu','hehe','dada','yyy']
dodo('xxx').dudu('yyy').osc(); // {dodo:'hehe', dudu: 'yyy'}, osc message ['dodo','hehe','dudu','yyy']
```

the param is also patternified by default:

```js
dudu("a [b c]") // {dudu:'a'}, {dudu:'b'}, {dudu:'c'}, 
```

### CODE REVIEW

**Comment by yaxu** [comment]
I think this could be useful enough to name them `param`/`params`

Also if `param` is called with > 1 parameter, how about it treats the remaining parameters as a sequence. Allowing:

```js
var dudu = param('dudu'); 
```
but also:
```js
param('dudu', 3, 4, 2).speed(2) 
param('dudu', "3 4 2").speed(2) 
```
Also as a pattern method:
```js
note("a3 a4").param('dudu', "3 4 2")
```
As sometimes you might want to send a one-time-only parameter.

In fact in tidal, this function is just `p` (although they have to be specialised with a type so `pF` for floats,, `pS` for strings etc)

**Comment by felixroos** [comment]
In that case `param('dud')` shouldn't add `.dudu` to Pattern i suppose?

**Comment by yaxu** [comment]
Hmm.  Maybe `param('dudu')` should but `param('dudu', <pattern>)` shouldn't?

**Comment by felixroos** [comment]
or just separate `param` and `createParam(s)` ?

**Comment by yaxu** [comment]
Yes could be..

**Comment by felixroos** [comment]
or maybe it looks cooler to do `Pattern.createParam('dududu')` . I think most of the time, there will be a hand full of custom patterns used that are created beforehand as a setup step, but still the `param(name, ...pats)` would be useful for inline usage and or patternified param names

**Comment by yaxu** [comment]
Hmm I think this is tangentially related to #34 . Being able to stick `pF` in patterns is particularly useful in tidal due to block based evaluation. When you evaluate everything then there's less cost to having separate statements.

**Comment by yaxu** [comment]
(I talked in a circle here but happy for you to merge whatever feels right!)

**Comment by felixroos** [comment]
I'll merge this now, we can add the inline param function in a separate feature

**Pull request merged**
