### PR TITLE
Add tidal-drum-patterns to examples

### PR DESCRIPTION
**Pull request by urswilke**
As discussed [here](https://github.com/tidalcycles/strudel/discussions/373#discussioncomment-4691189) this is a first draft to merge the tidal-drum-patterns to the main folder of the examples in the docs.

### CODE REVIEW

**Comment by felixroos** [comment]
hey! thanks for looking into this. could you add these to a separate file? tunes.mjs is used for the shuffle function in the repl. having this large number of drum patterns in there will make it really unlikely that the shuffle will pick a tune that is not a drum pattern..

**Comment by urswilke** [comment]
yes sure, should be fixed now. And I felt a bit bad to put all these patterns in your file, which really has some beautiful tunes :)

**Comment by felixroos** [comment]
should I just merge this and then add them to a dedicated page in a separate PR?

**Comment by urswilke** [comment]
that sounds great

**Pull request merged**
