### PR TITLE
Reset, Restart and other composers

### PR DESCRIPTION
**Pull request by felixroos**
https://github.com/tidalcycles/strudel/issues/53

### CODE REVIEW

**Comment by yaxu** [comment]
I think reconfiguring it into a join would be good, like in [this example](https://is.gd/rsTD1Z). Then we can easily make `_opReset` and `_opRestart` and add to the pattern composer family https://github.com/tidalcycles/strudel/blob/main/packages/core/pattern.mjs#L751-L767

**Comment by yaxu** [comment]
Now we have:

 . | In | Out | Mix | Squeeze | SqueezeOut | Trig | TrigZero |
| - | --- | -- | --- | --- | --- | --- | --- |
| add | add/addIn | addOut | addMix | addSqueeze | addSqueezeOut | addTrig | addTrigZero | 
| sub | add/subIn | subOut | subMix | subSqueeze | subSqueezeOut | subTrig | subTrigZero |

and the same for these operators:
```
set keep keepif mul  div  mod  pow  lt  gt  lte  gte  eq  eqt  ne  net  and  or _and  _or  _xor  _lshift  _rshift func
```
`keepif` only keeps for values on the 'outside' pattern (on the right) that are true (truthy), otherwise the value is undefined (for later removal with `_removeundefined()`).

`lt` is `<`, `gte` is `>=`, `eqt` is `===` etc.

All operators 'op' default to `opIn`, i.e. applying operator into the pattern on the left.

Then there are these aliases to give functions that deal only with structure not particular values:
struct = 
| alias | for |  
| - | - | 
| struct | keepifOut |
| structAll | keepif |
| mask | keepifIn |
| maskAll | keepifOut |
| reset | keepifTrig |
| resetAll | keepTrig |
| restart | keepifTrigZero |
| restartAll | keepTrigZero |

The `All` variants use all events from the outside pattern, not just the 'true' ones.

I'm happy with all this now. I'm just unsure whether `struct` etc should default to use all events, with the variant called e.g. `structBinary`

**Comment by felixroos** [comment]
I like the `in` `out` wording! Also good to have the aliases you mentioned. I guess I'd need to discover the utility of all those functions by using them. Maybe we will find some more aliases later.

**Comment by yaxu** [comment]
I think there will be some naming tweaks as well later, as we try them out.. But I think this is a good time to merge?

**Comment by felixroos** [comment]
yes, let's merge

**Pull request merged**
